### ISSUE TITLE
Illegal callback invocation from native module. This callback type only permits a single invocation from native code.

### ISSUE THREAD

**Issue by kylebesser** [RoJoHub/react-native-ping#112]
Not sure if anyone is still maintaining this code anymore but I am having an issue when calling Ping.start with multiple IP addresses.

This is my current code utilizing this library. My code is as follows:

`async function checkIPAddressValid(fourthOctet) {  //scanning the entire subnet on the fourth octect see if every ip address is alive
    let ipSplit;
    ipSplit = gatewayIPAddress.split('.');
    const ipaddress = ipSplit[0] + '.' + ipSplit[1] + '.' + ipSplit[2] + '.' + fourthOctet;
    // const myModuleEvt = new NativeEventEmitter(NativeModules.MyModule)

    await Ping.start(ipaddress, {timeout: 1000}).then((response) => {
        if (ipaddress !== gatewayIPAddress && ipaddress !== deviceIPAddress) {
            if (!ipList.includes(ipaddress)) {
                ipList.push(ipaddress);
                const defineResult = DoDefineAsync(ipaddress);
            }
        }
    }).catch((error) => {
        console.log(ipaddress: + ' ' + error + "\n");
    });
}`

This particular function is called approximately 255 times. It is fairly immediately and "works" to get the IP addresses that I am looking for but it constantly throws an RCTFatal error and the following message.

"Illegal callback invocation from native module. This callback type only permits a single invocation from native code."

Any help solving this would be greatly appreciated. Thank you.

**Comment by RoJoHub** [comment]
The current design only supports one ping at a time
