### ISSUE TITLE
Getting DNS error on startup

### ISSUE THREAD

**Issue by adriantache** [RoJoHub/react-native-ping#14]
I have integrated this module to detect for internet access by pinging Google DNS (8.8.8.8). This works just fine, but one of the first times it pings, on starting the app on iOS, the module throws a DNS error, despite me pinging an IP directly. 

This is the error message: 域名解析失败

I have resolved it by just triggering another ping if I get this error, but I think it is a bug. 

Looking at your code, I think this module should have a check and not try to resolve the IP for IPs.

**Comment by RoJoHub** [comment]
Could  you please provide some more information.
Because i also ping `8.8.8.8`.It's never reture error.
I want to konw what happened.
thank you very much!

**Comment by adriantache** [comment]
For me it only happens once, on the iOS simulator (I don't have a device to test on), on startup. The second ping I send returns that error, with every other ping working just fine. 

I think a quick fix is to not try to resolve hostnames if they match the regex of ip addresses.

**Comment by RoJoHub** [comment]
Thanks for you feedback.

The reason is that the request in the previous code has not been closed, and a new request is rejected by my code. 

So report the error.

（Slow connection speed causes new requests to be rejected）

I am thinking about making reasonable changes to the code.

**Comment by RoJoHub** [comment]
I am thinking about making reasonable changes to the code.

**Comment by RoJoHub** [comment]
The error message I wrote before was wrong. Not domain name resolution failed

**Comment by maxhis** [comment]
@RoJoHub Any updates? Same issue here.

**Comment by RoJoHub** [comment]
> @RoJoHub Any updates? Same issue here.

@maxhis  手机端由翻墙嘛?

**Comment by maxhis** [comment]
@RoJoHub 我是用的模拟器，把电脑的代理关掉也会报这个错。

**Comment by RoJoHub** [comment]
@maxhis @adriantache 

Please update to ` 1.1.4`

>Fix message of error on iOS

**Comment by RoJoHub** [comment]
> @RoJoHub 我是用的模拟器，把电脑的代理关掉也会报这个错。

这个问题是由于....上一次的 ping 操作还在运行....想作为 feature 优化来着

**Comment by RoJoHub** [comment]
@maxhis 

Please update to `1.2.0`.
This feature has been added in version `1.2.0`.
