### ISSUE TITLE
How to set timeout

### ISSUE THREAD

**Issue by Enoooch** [RoJoHub/react-native-ping#25]
Error:Can't setup.The previous request is still running.
I have several local IP address to ping, if one down, others are down too.
new feature request:
await Ping.start('192.168.1.111', { timeout: 1500 })

**Comment by RoJoHub** [comment]
This api is not open yet. But it may be released tonight.

**Comment by Enoooch** [comment]
OK, is there any link about this update?

And is there any way to stop the promise manually？
let res = Ping.start('192.168.1.111')
res.reject()

Have to stop the promise manually, because the process is too long.

**Comment by RoJoHub** [comment]
Maybe you should use `async/await`?

```javascript
    setTimeout(async () => {
      try {
        const ms = await Ping.start('114.114.114.114');
      } catch (error) {
        console.log('something happened', error);
      }
    }, 1000);
```

---

If any update,i will push to `github` and publish on `npm`.

**Comment by Enoooch** [comment]
Thanks. I'll wait, but setTimeout is still not a solution.

**Comment by RoJoHub** [comment]
Please update to `1.2.0`.
This feature has been added in version `1.2.0`.
