### ISSUE TITLE
Bad Address Causes Repeated Failure

### ISSUE THREAD

**Issue by ajones2k** [RoJoHub/react-native-ping#27]
If I ping a good address
ms = await Ping.start('8.8.8.8'); //works

then a bad address
ms = await Ping.start('8.8.8.9'); //fails

then trying to ping the good address again always fails unless I restart the app
ms = await Ping.start('8.8.8.8'); //fails

Is there anyway to 'reset' the library to prevent this problem.

**Comment by RoJoHub** [comment]
Please update to `1.2.0`.
This problem has been fixed in version `1.2.0`.

**Comment by ajones2k** [comment]
Works perfectly. Thanks so much for your help!!

/Alan
________________________________
