### ISSUE TITLE
iOS build error: fatal error: 'LHDefinition.h' file not found

### ISSUE THREAD

**Issue by maxhis** [RoJoHub/react-native-ping#28]
Compile error after upgrading to version 1.2.0.

```
node_modules/react-native-ping/ios/GBPing/GBPing.m:6:9: fatal error: 'LHDefinition.h' file not found
#import "LHDefinition.h"
```

**Comment by RoJoHub** [comment]
![image](https://user-images.githubusercontent.com/15648309/55289196-d5c41080-53f5-11e9-952c-9f0cbc946e04.png)

Maybe you should clean cache of xcode ?

**Comment by maxhis** [comment]
Tried and not working. BTW, I'm using the latest version(10.2) of Xcode.

**Comment by RoJoHub** [comment]
`rm -rf  node_modules && yarn`
Please try again.

**Comment by RoJoHub** [comment]
I created a new project. Introduced the library. It works fine iOS.
@maxhis

**Comment by maxhis** [comment]
Worked with Xcode building, and still got the error while running with `react-native run-ios`.

**Comment by RoJoHub** [comment]
Hello. Is it convenient for you to create an Example on github? So I can understand the specific situation.

I did not find this problem because I created a new react native project and introduced this repository.

**Comment by maxhis** [comment]
Thanks, @RoJoHub. Tried your example, it did work on my side. So It should be something else wrong affect my problems.

**Comment by maxhis** [comment]
OK, finally I got it to work. For anyone facing the same issue: Try deleting the build folder `<your-project>/ios/build` and then run `react-native run-ios` again.
