### ISSUE TITLE
 error: reference to reject is ambiguous

### ISSUE THREAD

**Issue by compski** [RoJoHub/react-native-ping#30]
BUILD FAILED in 5s
15 actionable tasks: 12 executed, 3 up-to-date
error Could not install the app on the device, read the error above for details.
Make sure you have an Android emulator running or a device connected and have
set up your Android development environment:
https://facebook.github.io/react-native/docs/getting-started.html
error Command failed: gradlew.bat app:installDebug. Run CLI with --verbose flag for more details.

C:\Users\username\Documents\JS projects\pingtest>react-native run-android
info Starting JS server...
info Building and installing the app on the device (cd android && gradlew.bat app:installDebug)...

> Configure project :app
WARNING: Configuration 'compile' is obsolete and has been replaced with 'implementation' and 'api'.
It will be removed at the end of 2018. For more information see: http://d.android.com/r/tools/update-dependency-configurations.html

> Task :react-native-ping:compileDebugJavaWithJavac
C:\Users\username\Documents\JS projects\pingtest\node_modules\react-native-ping\android\src\main\java\com\reactlibrary\RNReactNativePingModule.java:28: error: reference to reject is ambiguous
            promise.reject(error.getCode(), error.getMessage(), null);
                   ^
  both method reject(String,String,Throwable) in Promise and method reject(String,String,WritableMap) in Promise match
C:\Users\username\Documents\JS projects\pingtest\node_modules\react-native-ping\android\src\main\java\com\reactlibrary\RNReactNativePingModule.java:54: error: reference to reject is ambiguous
                    promise.reject(error.getCode(), error.getMessage(), null);
                           ^
  both method reject(String,String,Throwable) in Promise and method reject(String,String,WritableMap) in Promise match
C:\Users\username\Documents\JS projects\pingtest\node_modules\react-native-ping\android\src\main\java\com\reactlibrary\RNReactNativePingModule.java:67: error: reference to reject is ambiguous
                promise.reject(error.getCode(), error.getMessage(), null);
                       ^
  both method reject(String,String,Throwable) in Promise and method reject(String,String,WritableMap) in Promise match
3 errors

> Task :react-native-ping:compileDebugJavaWithJavac FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-ping:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 7s
15 actionable tasks: 1 executed, 14 up-to-date
error Could not install the app on the device, read the error above for details.
Make sure you have an Android emulator running or a device connected and have
set up your Android development environment:
https://facebook.github.io/react-native/docs/getting-started.html
error Command failed: gradlew.bat app:installDebug. Run CLI with --verbose flag for more details.

**Comment by maxhis** [comment]
Same here. 

Changing all `promise.reject(error.getCode(), error.getMessage(), null);` to `promise.reject(error.getCode(), error.getMessage());` in `RNReactNativePingModule.java` can fix the compile error.

However, got a new error: 
```
Attempt to invoke interface method 'boolean com.facebook.react.bridge.ReadableMap.hasKey(java.lang.String)' on a null object reference
start
    RNReactNativePingModule.java:34
```

My workaround is replacing the line 34 `if (option.hasKey(TIMEOUT_KEY)) {` to `if (option != null && option.hasKey(TIMEOUT_KEY)) {`

**Comment by RoJoHub** [comment]
@compski @maxhis 
Hi guys😀
I wil fix this problem in `1.2.1`.
---
The reason for this problem is that the `0.58` version of react native has changed. But it is now compatible.

https://github.com/react-native-community/react-native-releases/blob/master/CHANGELOG.md

> [0.58] => Added => Android specific
>
> * Native Modules can now reject a promise with an additional WritableMap arg for extra properties (userInfo). See the interface defined in Promise.java for available methods. This is accessible in JavaScript as Error.userInfo. This is to match iOS's existing Error.userInfo behaviour. See PR for examples. (#20940 by @Salakar)

**Comment by bogdandobritoiu** [comment]
Still not fixed, checked 1.2.2. I can confirm what @maxhis did works

**Comment by RoJoHub** [comment]
> Still not fixed, checked 1.2.2. I can confirm what @maxhis did works

Please run `example` for test.
It seem to ok in `example`

**Comment by bogdandobritoiu** [comment]
Line 34 is still the same. Tried it on my local machine and it works as suggested by @maxhis .

if (option.hasKey(TIMEOUT_KEY)) { 
with 
if (option != null && option.hasKey(TIMEOUT_KEY)) {

**Comment by RoJoHub** [comment]
> Line 34 is still the same. Tried it on my local machine and it works as suggested by @maxhis .
> 
> if (option.hasKey(TIMEOUT_KEY)) {
> with
> if (option != null && option.hasKey(TIMEOUT_KEY)) {

Could you please tell which version version you use?
`React Native` And `react-native-ping`

**Comment by bogdandobritoiu** [comment]
"react-native-ping": "^1.2.2",
"react-native": "^0.59.8",

**Comment by RoJoHub** [comment]
Please watch `package-lock.json` or `yarn.lock`.
Check if the version of `react-native-ping`

![image](https://user-images.githubusercontent.com/15648309/59176078-86832480-8b8a-11e9-856b-d8f28ba50073.png)

![image](https://user-images.githubusercontent.com/15648309/59176092-91d65000-8b8a-11e9-9e43-a9637b7ee4c9.png)

**Comment by bogdandobritoiu** [comment]
Ah yes, my lock.json had the wrong version. Sorry for the misunderstanding! Thank you for quick responses
