### ISSUE TITLE
Cannot read property 'start' of undefined

### ISSUE THREAD

**Issue by tahagit** [RoJoHub/react-native-ping#37]
Hello 
I've this error in log: 

special code undefined Cannot read property 'start' of undefined

**Comment by RoJoHub** [comment]
Could you please tell which version you use?

**Comment by tahagit** [comment]
> Could you please tell which version you use?

V1.2.2
And i’m using the last version of react and react native

**Comment by RoJoHub** [comment]
Hi.
I find solution  for it .

----

## Firstly, We should unlink the dependence.

```
$ react-native unlink react-native-ping
```

---

## Secondly 

go to  `rootPath/ios/`

And **Run**

```
$ pod install
```
