### ISSUE TITLE
Android package name

### ISSUE THREAD

**Issue by iwashi1t** [RoJoHub/react-native-ping#41]
The Android package name "com.reactlibrary" is too general, so can you change it to something else?

Duplicate error has occurred when used with a library with the same package name "com.reactlibrary".

**Comment by Samuelsolano8** [comment]
the library work for you ?

**Comment by iwashi1t** [comment]
In my case, I was using another library with the package name "com.reactlibrary", so the release build failed due to a "Duplicate Package Name" error.

Currently, the problem has not occurred because the library has fixed it, but I think that it is better to change it because there are cases where the same problem occurs.

**Comment by RoJoHub** [comment]
Hi guy.Sorry,I'm lateter.

Maybe it is work for you.

put it to `build.gradle`

```
android {
    compileSdkVersion 23
    buildToolsVersion "23.0.1"
    enforceUniquePackageName = false
    ...
}
```

**Comment by iwashi1t** [comment]
Thank you, the solution will probably work for build errors.

On the other hand, apparently you don't intend to change the package name, so I close this issue.

**Comment by Macrow** [comment]
enforceUniquePackageName参数已经废弃，能否将报名更改一下，这个名字确实太容易重复了，编译会出错，`aliyun-oss-react-native`里面的包名就和这个一模一样。

```
Error: Type com.reactlibrary.BuildConfig is defined multiple times
```

**Comment by RoJoHub** [comment]
> enforceUniquePackageName参数已经废弃，能否将报名更改一下，这个名字确实太容易重复了，编译会出错，`aliyun-oss-react-native`里面的包名就和这个一模一样。
> 
> ```
> Error: Type com.reactlibrary.BuildConfig is defined multiple times
> ```


感谢提醒

**Comment by RoJoHub** [comment]
hi guys , package name is modify.
please use version of 1.2.5
