### ISSUE TITLE
special code undefined null is not an object (evaluating 'RNReactNativePing.start')

### ISSUE THREAD

**Issue by Samuelsolano8** [RoJoHub/react-native-ping#42]
actualy i.m using expo cli to develop in react native but for use you native module i was need to use "expokit" because that is the way to use native modules in react native expo but i have the same mistake when i use expo cli than i use Expokit the issue is "special code undefined null is not an object (evaluating 'RNReactNativePing.start')" can you help me?

**Comment by RoJoHub** [comment]
I'm sorry.
I have been busy with other things in recent months.
It seem that the app is created by Expo?

...Oh.......I have not used Expo.
But we can solve this problem by use react-native-cli.

**Comment by HenriqueMata** [comment]
Same problem, but with react-native-cli.

**Comment by ratzxx** [comment]
Yeah, same error with Expo

**Comment by willnaoosmit** [comment]
Same error without Expo

**Comment by willnaoosmit** [comment]
You can solve this by running:

react-native link react-native-ping
npx jetify

**Comment by alfredd2001** [comment]
Didn't fixed for me

**Comment by alfredd2001** [comment]
Alright, fixed it by running again react_native run-android, this automatically makes the jetify at the beginning so don't worry about it
