### ISSUE TITLE
Not able to ping a url.

### ISSUE THREAD

**Issue by ednew2018** [RoJoHub/react-native-ping#44]
Ping "youtube.com" or other url will result in error "PingUtil_Message_HostErrorNotSetHost". We sometimes use it to ping DDNS server.

**Comment by RoJoHub** [comment]
Could you please me tell me which version you use ?

**Comment by ednew2018** [comment]
1.2.2 and used `npm install react-native-ping`

**Comment by RoJoHub** [comment]
Maybe you should pay attentiom to `package-lock.json`?
The version is error in this file.

**Comment by RoJoHub** [comment]
Maybe you should pay attentiom to package-lock.json?
The version of react-native-ping  is error in this file.

**Comment by ednew2018** [comment]
My mistake. It works.

**Comment by RoJoHub** [comment]
> My mistake. It works.

😀
