### ISSUE TITLE
Cannot ping a server

### ISSUE THREAD

**Issue by MasoudShah** [RoJoHub/react-native-ping#45]
No matter witch server, it always returns PingUtil_Message_HostErrorUnknown. I'm using it for Android.

**Comment by RoJoHub** [comment]
Could you please tell me  which version do you use?

**Comment by MasoudShah** [comment]
The project is initiated with react native version 0.61.5 and I used the last version of react-native-ping witch is 1.2.2.

**Comment by MasoudShah** [comment]
So sorry that was my fault in making mistake of using async properly in promises.

**Comment by MasoudShah** [comment]
The project is initiated with react native version 0.61.5 and I used the last version of this library witch is 1.2.2.

**Comment by MasoudShah** [comment]
Still no solution for this?

**Comment by mightywarriors946** [comment]
Same issue on Android.. It works First Time, then returns error code 3 mostly..

**Comment by RoJoHub** [comment]
Sorry,i am so late.
@mightywarriors946  @MasoudShah 
Because the last ping request has not been completed, you must wait for the request to complete

**Comment by ABRAR-E-GOHAR** [comment]
Same issue of PingUtil_Message_HostErrorUnknown

**Comment by RoJoHub** [comment]
> Same issue of PingUtil_Message_HostErrorUnknown

Could you please tell me domain or ip adress?
And which platform.
