### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by NikolasRoger** [RoJoHub/react-native-ping#46]
![image](https://user-images.githubusercontent.com/34105313/81483760-f4aaee00-9216-11ea-9789-1a8abbf5c7b4.png)

Error when i try assembleRelease or bundleRelease

react native version: 0.62.2
"react-native-ping": "^1.2.2"

**Comment by RoJoHub** [comment]
Are your project of android support androidx?
Maybe you should edit `import android.support.v4.util.ArrayMap;` to `import androidx.collection.ArrayMap;` 
For example, edit the following lines to `nodo_module/react-native-ping/android/src/main/java/com/reactlibrary/PingUtil.java`

```diff
package com.reactlibrary;

- import android.support.v4.util.ArrayMap;
+ import androidx.collection.ArrayMap;

import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.net.URI;
import java.util.regex.Pattern;
```
