### ISSUE TITLE
Pinging non-existent IP never completes promise iOS

### ISSUE THREAD

**Issue by ajones2k** [RoJoHub/react-native-ping#50]
Calling the ping function with an ip like 2.34.5.6 which does not exist causes the promise on the start functions to never complete. The code hangs at line 379 in the GBPing.m file. 

bytesRead = recvfrom(self.socket, buffer, kBufferSize, 0, (struct sockaddr *)&addr, &addrLen);

A timeout can be added with the following code right before the socket call. This is a timeout of 5 seconds. 

    struct timeval tv;
    tv.tv_sec = 5;
    tv.tv_usec = 0;
    if (setsockopt(self.socket, SOL_SOCKET, SO_RCVTIMEO,&tv,sizeof(tv)) < 0) {
        NSLog(@"Set Timeput Error");
    }

This does keep the function from hanging at this point, however it still does not cause a reject on the promise. It would be helpful to be able to exit with a reject on the promise if the socket timeout occurs.

**Comment by RoJoHub** [comment]
I have update code for this issue.
Thank you.   My friend.
😊
