### ISSUE TITLE
PingUtil_Message_HostErrorUnknown

### ISSUE THREAD

**Issue by kitchanismo** [RoJoHub/react-native-ping#56]
// google IP 172.217.24.46
// version 1.2.4
//
 // "react": "16.13.1",
  //  "react-native": "0.63.0",
try {
      const ms = await Ping.start('172.217.24.46', {timeout: 1000});
      console.log(ms);
    } catch (error) {
      console.log('special code', error.code, error.message);
    }

**Comment by micbaumr** [comment]
Same here. Does not work on android 10 when network type is 'cellular'. When network type is 'wifi' ping works fine. Any solutions?

**Comment by RoJoHub** [comment]
> 172.217.24.46

sorry , ip (172.217.24.46) is fail?

**Comment by RoJoHub** [comment]
> Same here. Does not work on android 10 when network type is 'cellular'. When network type is 'wifi' ping works fine. Any solutions?

Here are a few possible explanations。
1. Maybe you have a permission problem？ 
[please add this code to AndroidManifest.xml ](https://developer.android.com/training/basics/network-ops/connecting)

```
<uses-permission android:name="android.permission.INTERNET" />
<uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
```

2. react-native must be connected to wifi in debug mode, not a module issue

**Comment by RoJoHub** [comment]
> Same here. Does not work on android 10 when network type is 'cellular'. When network type is 'wifi' ping works fine. Any solutions?

> Same here. Does not work on android 10 when network type is 'cellular'. When network type is 'wifi' ping works fine. Any solutions?

Here are a few possible explanations。
1. Maybe you have a permission problem？ 
[please add this code to AndroidManifest.xml ](https://developer.android.com/training/basics/network-ops/connecting)

```
<uses-permission android:name="android.permission.INTERNET" />
<uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
```

2. react-native must be connected to wifi in debug mode, not a module issue
