### ISSUE TITLE
Error After integrating this package on android. 

### ISSUE THREAD

**Issue by prakashw3expert** [RoJoHub/react-native-ping#57]
<img width="1345" alt="Screenshot 2020-08-20 at 1 50 51 PM" src="https://user-images.githubusercontent.com/9264905/90739175-35250800-e2ec-11ea-94f9-3a3ff2802d20.png">
got this error 
execution failed for task ':app:multiDexListDebug'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
   > Error while merging dex archives: 
RN 0.60.4

**Comment by RoJoHub** [comment]
The error message is not very clear.

Maybe you should see that [MultiDex issue - Execution failed for task ':app:dexDebug'](https://stackoverflow.com/questions/30104925/multidex-issue-execution-failed-for-task-appdexdebug)

**Comment by bodaghialib4** [comment]
Hi,
I got the similar error too.

```
* What went wrong:
Execution failed for task ':app:transformClassesWithMultidexlistForDebug'.
> com.android.build.api.transform.TransformException: Error while generating the main dex list:
  Error while merging dex archives: 
  Learn how to resolve the issue at https://developer.android.com/studio/build/dependencies#duplicate_classes.
  Program type already present: com.reactlibrary.BuildConfig

```
I googled the last line of error and find out the source of error (as described in below link):

https://stackoverflow.com/questions/50717588/program-type-already-present-buildconfig


the android package name of this module is `com.reactlibrary`. 
one of my previous installed modules (`react-native-ssh-sftp`) has the android package name as same as  `com.reactlibrary`. and this causes this error.
