### ISSUE TITLE
Error with V.1.2.5

### ISSUE THREAD

**Issue by poptanai** [RoJoHub/react-native-ping#63]
error: package LHDefinition does not exist
            LHDefinition.PING_ERROR_CODE error = LHDefinition.PING_ERROR_CODE.HostErrorNotSetHost;

**Comment by poptanai** [comment]
There is no "import ...LHDefinition" in the module.

**Comment by RoJoHub** [comment]
> There is no "import ...LHDefinition" in the module.

Please use v1.2.6
