### ISSUE TITLE
npm install react-native-ping not working 

### ISSUE THREAD

**Issue by aquilusnorman** [RoJoHub/react-native-ping#65]
## npm install react-native-ping command not working 

npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: undefined@undefined
npm ERR! Found: react-native@0.63.4
npm ERR! node_modules/react-native
npm ERR!   react-native@"~0.63.4" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer react-native@"^0.41.2 || ^0.57.0" from react-native-ping@1.2.6
npm ERR! node_modules/react-native-ping
npm ERR!   react-native-ping@"*" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.

**Comment by RoJoHub** [comment]
please use `yarn` or `rm -rf node_modules && npm install react-native-ping`

**Comment by avonipenti** [comment]
This does not work as well
