### ISSUE TITLE
I am getting " cannot find symbol  : packages.add(new RNReactNativePingPackage());"

### ISSUE THREAD

**Issue by shrutiraoniit25** [RoJoHub/react-native-ping#79]
here is my code screenshot
![Screenshot (7)](https://user-images.githubusercontent.com/42043257/117979258-5634f980-b350-11eb-94d3-e858ff5b5adf.png)
![Screenshot (8)](https://user-images.githubusercontent.com/42043257/117979267-57febd00-b350-11eb-8e55-3c4f11be5e48.png)

**Comment by RoJoHub** [comment]
Please check your `build.gradle`.
