### ISSUE TITLE
Set Interval Cannot Reset

### ISSUE THREAD

**Issue by rival14** [RoJoHub/react-native-ping#90]
`        if (start) {
            clearInterval(interval)
            setStart(false)
          }else{
            setStart(true)
            interval = setInterval(() => {
              Ping.start('8.8.8.8', { timeout: 1000 }).then(ms => {
                setMs(ms);
                data.push(ms);
                console.log(ms)
              }).catch(err => console.log(err));
            }, 1000);
          }`
          
SetInterval cannot stop the ping request, so the request always sent and cannot stopped

**Comment by RoJoHub** [comment]
I'm fine here. Please provide more information.
